version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: interview_orchestrator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/interview_orchestrator
    depends_on:
      - postgres

volumes:
  postgres_data:
